version: "3.4"

# web (front-end) depends on api (back-end) depends on (db)
# nginx -> web -> api -> db [dependency chain]

volumes:
  web_node_modules:
  postgres_data:

services:
  yacs_nginx:
    container_name: yacs_nginx
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./src/web/nginx.development.conf:/etc/nginx/nginx.conf
    depends_on:
      - yacs_web

  yacs_web:
    build:
      target: develop-stage
    command: npm run serve
    ports:
      - 8080:8080
    volumes:
      - ./src/web:/app
      - web_node_modules:/app/node_modules/
    environment:
      - YACS_API_HOST=http://yacs_api:5000

  yacs_api:
    command: /bin/bash -c "python tables/database_session.py && PYTHONPATH=. alembic upgrade head && uvicorn app:app --reload --host 0.0.0.0 --port 5000"
    ports:
      - 5000:5000
    volumes:
      - ./src/api:/usr/src
    environment:
      - ENV=development
      - DEBUG=True
      - DB_HOST=yacs_db
      - DB_USER=yacs
      - DB_PASS=${DB_PASS:-easy_dev_pass}
      - DB_NAME=yacs
      - DB_PORT=5432
      - API_SIGN_KEY=${API_SIGN_KEY:-secretKey}

  yacs_db:
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=yacs
      - POSTGRES_USER=yacs
      - POSTGRES_PASSWORD=${DB_PASS:-easy_dev_pass}

  redis:
    image: redis:latest
    container_name: yacs_redis

  celery:
    container_name: yacs_celery
    build:
      context: ./src/worker/
      dockerfile: Dockerfile
    command: celery -A celery_app worker --loglevel=info
    volumes:
      - ./src/worker:/app
    depends_on:
      - redis

