on:
  schedule:
    - cron: '0 5 * * *' # at midnight EST, drop all running vms to save money

jobs:
  drop_temp_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x

      - name: Drop Infrastructure
        run: |
          cd ops/
          npm install
          node drop-infra.js
        env:
          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}
